language: python3
install: 
- pip3 install django
- pip3 install djangorestframework
- pip3 install django-cors-headers
script:
- pytest calpolyrides/api/tests.py
dist: trusty
addons:
  sonarcloud:
    organization: "kclever"
    token:
      secure: "H6M4Gzm6HVSJUB1u3DhYIPIPYURPt8GoaXEi1O2AtyOvqW3yXKR6WmkXUx6kA+BEGkBugplmmkEzM6gqYGXk3BXPy4CjM/JN9Napegd+KQxYPXjvIOY8LHmaWp/dTfKzRr35pDujwmo3jGTs4kXk5iH0vv1ZfYCZ8DSnvdL5gawXR7+EZtdZ8PD/4uT8/j7eCYXxLauk0of9Vx/JeltEWJNXwvkodgKiFzCeLk7ROimpigZTSuvH8dUTaLRPoW2svCw/7fLmYRMh5I91qEjQwJV3ac3aoJI7ISWLf8FR8LM0QWBUdvz5W5fvTuNsMpO2DzhKY/MILtXQEgagIuMu9k2W2/VKtgqz/Kla3sZquMs+wSYB805X25rZ3n0pbTOd5SJpDek7cwkCj/nPLfDiu2BFs8Sl1wNrw8ZJ57ID1drpFzASev1lZ/8oIynbTdMXN+lg6MeunsLhqa0FShxkAZbA8NZCKpVtpOI1KEhJLXqcps/74bDKGEie7sfRWPW3FXnUUUviwWjlmSWKncCGLEPt86xCPSSdKpAd/UfE3/IXgwyVNLJRJTMMTYyPb/qbe/cbT/FATQXX7YbKabaAsNWaf2/76i5344wQ+rypMwZy/ulbwWjCfBLvHVw3UbxmA/vde3+57GwToROaD7575ujX3GFEBBVUyHdUyzroUwk=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner