language: python3
install: 
- pip3 install django
- pip3 install djangorestframework
- pip3 install django-cors-headers
script:
- pytest calpolyrides/api/tests.py

dist: trusty

addons:
  sonarcloud:
    organization: "kclever"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner