# Generated by Django 3.0 on 2019-12-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_u', models.CharField(max_length=100, verbose_name='Name')),
                ('from_u', models.CharField(max_length=100, verbose_name='From')),
                ('to_u', models.CharField(max_length=100, verbose_name='To')),
                ('when_u', models.DateTimeField(verbose_name='When')),
                ('seats_u', models.IntegerField(verbose_name='Seats')),
                ('cost_u', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cost')),
                ('will_drop_u', models.BooleanField(verbose_name='Willing to drop along the way')),
                ('extra_details_u', models.TextField(max_length=500, verbose_name='Extra Details')),
            ],
        ),
    ]
